FORMAT: 1A
HOST: https://allflex.sureflap.com

# SureSense App API
The Allflex API will be the communication end point of the app.

The purpose of the api is to:

* Be the communication end point of the application.
* Process app logins and generate/ authenticate  login tokens.
* Accept sensor input through the app.
* All download of historic sensor data.
* Allow control  over shared data and have the ability to revoke access.

_The API will be written in PHP using the Laravel Framework, conforming to RESTful standards_

# Group Authentication

## Security
All requests submitted to the API require an `X-Authorization` header set.

The authorisation token is a base64-encoded sha512 hashed password. 

Example token: `$2y$10$Fxu/T7vBmNtEGNz3CVMIFO1aCSMzVxBMzDdpjSzBn4Y0dBXBDWCIW`

Example failed auth attempt:
        
        {
            "error": true,
            "errors": {
                "Authorization": [
                    {
                        0:  "error.auth.header-missing"
                    }
                ]
            }
        }

Always use SSL. No exceptions. This way we are guaranteed that encrypted communications simplifies authentication efforts. 

Attempts to use the non-ssl version will trigger a hard error.

        {
            "status": 400
            "errors": [
                {
                    "code": 30000,
                    "message": "Insecure connection"
                }
            ]
        }
        
# Group User
        
## api.user.login [/api/user/login]
### Attempt post user login [POST]

You can use this method to authenticate a user with a valid email and password. This will in turn generate a token.

+ Request (application/json)

    + Headers
    
    + Body
            
            {
                "email_address": "a.hunter@sureflap.co.uk",
                "password": "changeme"
            }

+ Response 200 (application/json)

        {
            "error": false,
            "result": [
                {
                    "token": [
                        {
                            "token": "$2y$10$1jI2k3fWpjFtyw03eklRn.hITTK.vgMdAVA3SObblqupGJDyxdpLi",
                            "expires_at": "2015-02-24 10:09:47",
                            "created_at": "2015-02-17 10:09:47"
                        }
                    ],
                    "user": [
                        {
                            "id": "16",
                            "first_name": "Bob",
                            "last_name": "Hunter",
                            "email_address": "a.hunter@sureflap.co.uk",
                            "telephone": "07403243457",
                            "image_path": null,
                            "created_at": "2015-02-09 14:00:02",
                            "updated_at": "2015-02-10 15:22:55"
                        }
                    ]
                }
            ]
        }
        
## api.user.logout [/api/user/logout]
### Attempt user logout [POST]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Response 201 (application/json)

            {
                "error": false,
                "message": "You are now logged out"
            }

## api.user [/api/user]
### Create a user account [POST]

Get the basic information needed to create an account.

+ Request (application/json)
            
        {
            "first_name": "John",
            "last_name": "Doe",
            "email": "j.doe@sureflap.com",
            "telephone": "01223432654",
            "password": "changme",
        }

+ Response 201 (application/json)

        {
            "error": false,
            "result": {
                "first_name": "John",
                "last_name": "Doe",
                "email": "j.doe@sureflap.co.uk",
                "telephone": "01223 432654",
                "updated_at": "2015-02-17 10:19:44",
                "created_at": "2015-02-17 10:19:44",
                "id": 15
            }
        }

## api.user.{id} [/api/user/{id}]
### Get information on user account [GET]

+ Request

    + Headers
    
            X-Authorization: <token>
            
+ Parameters
    + id

+ Response 200 (application/json)

        {
            "error": false,
            "result": {
                "id": 15,
                "first_name": "John",
                "last_name": "Doe",
                "email": "j.doe@sureflap.co.uk",
                "telephone": "01223 432654",
                "created_at": "2015-02-17 10:19:44",
                "updated_at": "2015-02-17 10:19:44"
            }
        }
        
### Update user account [PUT]

+ Request

    + Headers
    
            X-Authorization: <token>
            
    + Body
    
            {
                "email": "j.doe@sureflap.com"
            }

+ Parameters
    + id
    
+ Response 200 (application/json)

        {
            "error": false,
            "result": {
                "id": 15,
                "first_name": "John",
                "last_name": "Doe",
                "email": "j.doe@sureflap.com",
                "telephone": "01223 432654",
                "created_at": "2015-02-17 10:19:44",
                "updated_at": "2015-02-17 11:18:19"
            }
        }
        
### Delete user account [DELETE]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + id
    
+ Response 200 (application/json)

        {
            "error": false
        }
        
## api.pet [/api/pet]

### Get all pets on account [GET]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Response 201 (application/json)

        {
            "error": false,
            "result": [
                {
                    "id": 13,
                    "name": "Jerry",
                    "microchip_number": "5746352413",
                    "breed": "Chihuahua",
                    "date_of_birth": "2012-12-12",
                    "weight": 5,
                    "size": "s",
                    "gender": "Male",
                    "user_id": 16
                },
                    "id": 14,
                    "name": "Milly",
                    "microchip_number": "1234555555",
                    "breed": "Chihuahua",
                    "date_of_birth": "2012-12-13",
                    "weight": 4.7,
                    "size": "s",
                    "gender": "Female",
                    "user_id": 16
                }
            ]
        }

### Create a pet account [POST]

Get the basic information needed to create an account.

+ Request

    + Headers
    
            X-Authorization: <token>

+ Request (application/json)
            
        {
            "name": "Jerry",
            "microchip_number": "5746352413",
            "breed": "Chihuahua",
            "date_of_birth": "2012-12-12",
            "weight": 5,
            "size": "s",
            "gender": "Male"
        }

+ Response 201 (application/json)

        {
            "error": false,
            "result": {
                "name": "Jerry",
                "microchip_number": "5746352413",
                "breed": "Chihuahua",
                "date_of_birth": "2012-12-12",
                "weight": 5,
                "size": "s",
                "gender": "Male",
                "image_path": "mydog.jpg",
                "id": 13,
                "user_id": 16
            }
        }

## api.pet.{id} [/api/pet/{id}]
        
### Update pet on account [PUT]

+ Request

    + Headers
    
            X-Authorization: <token>
            
    + Body
    
            {
                "name": "Milly Mii"
            }

+ Parameters
    + id
    
+ Response 200 (application/json)

        {
            "error": false,
            "result": {
                "id": 14,
                "name": "Milly Mii",
                "microchip_number": "1234555555",
                "breed": "Chihuahua",
                "date_of_birth": "2012-12-13",
                "weight": 4.7,
                "size": "s",
                "gender": "Female",
                "user_id": 16
            }
        }
        
### Delete pet [DELETE]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + id
    
+ Response 200 (application/json)

        {
            "error": false
        }
        
## api.device [/api/device]

### Get all devices on account [GET]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Response 201 (application/json)

        {
            "error": false,
            "result": [
                {
                    "id": 3,
                    "serial_id": "1234565",
                    "user_id": 1,
                    "vet_id": null,
                    "device": "first edition",
                    "name": null,
                    "version": "1.0",
                    "field_1": null,
                    "field_2": null,
                    "field_3": null,
                    "field_4": null
                },
                    "id": 4,
                    "serial_id": "1234565",
                    "user_id": null,
                    "vet_id": 1
                    "device": "first edition",
                    "name": null,
                    "version": "1.0",
                    "field_1": "Data",
                    "field_2": null,
                    "field_3": null,
                    "field_4": null
                }
            ]
        }

### Create a device [POST]

Get the basic information needed to create a device.

+ Request

    + Headers
    
            X-Authorization: <token>

+ Request (application/json)
            
        {
            "serial_id": "1234565",
            "device": "first edition",
            "version": "1.0",
            "user_id": 1
        }

+ Response 201 (application/json)

        {
            "error": false,
            "result": {
                "id": 4
            }
        }
        
## api.device.{id} [/api/device/{id}]

### Update a device [PUT]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Request (application/json)
            
        {
            "field_1": "Data"
        }

+ Response 201 (application/json)
        
        {
            "error": false,
            "result": {
                "id": 4
            }
        }

### Delete a device [DELETE]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + id
    
+ Response 200 (application/json)

        {
            "error": false
        }

## api.pet.{pet_id}.condition [/api/pet/{pet_id}/condition]

### Get all known conditions for pet [GET]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Response 201 (application/json)

        {
            "error": false,
            "result": [
                {
                    "0":  {
                        "id": 8,
                        "animal_id": 14,
                        "condition_id": 2
                    },
                    "1":  {
                        "id": 9,
                        "animal_id": 14,
                        "condition_id": 1
                    },
                    "2":  {
                        "id": 10,
                        "animal_id": 14,
                        "condition_id": 5
                    }
                }
            ]
        }

### Add a condition to an pet [POST]

Get the basic information needed to create an account.

+ Request

    + Headers
    
            X-Authorization: <token>

+ Request (application/json)
            
        {
            "condition_id": 4
        }

+ Response 201 (application/json)

        {
            "error": false,
            "result": {
                "condition_id": 4,
                "pet_id": 14
            }
        }
        
## api.pet.{pet_id}.condition.{id} [/api/pet/{pet_id}/condition/{id}]
        
### Delete pet condition [DELETE]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + pet_id
    + id
    
+ Response 200 (application/json)

        {
            "error": false
        }
        
## api.pet.{pet_id}.reading [/api/pet/{pet_id}/reading]

### Get all readings for a pet [GET]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Response 201 (application/json)

        {
            "error": false,
            "result": [
                {
                    "0":  {
                        "id": 34,
                        "pet_id": 14,
                        "temperature": 37.5
                    },
                    "1":  {
                        "id": 35,
                        "pet_id": 14,
                        "temperature": 37.7
                    },
                    "2":  {
                        "id": 40,
                        "pet_id": 14,
                        "temperature": 37.6
                    },
                    "3":  {
                        "id": 37,
                        "pet_id": 14,
                        "temperature": 37.5
                    },
                    "4":  {
                        "id": 38,
                        "pet_id": 14,
                        "temperature": 37.6
                    }
                }
            ]
        }

### Create new reading for a pet [POST]

Get the basic information needed to create an account.

+ Request

    + Headers
    
            X-Authorization: <token>

+ Request (application/json)
            
        {
            "temperature": 37.6
        }

+ Response 201 (application/json)

        {
            "error": false,
            "result": {
                "pet_id": 14,
                "id": 38
            }
        }
        
## api.pet.{pet_id}.reading.{id} [/api/pet/{pet_id}/reading/{id}]

### Get pet reading by id [GET]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + pet_id
    + id
    
+ Response 200 (application/json)

        {
            "error": false,
            "result": {
                "id": 40,
                "pet_id": 14,
                "temperature": 37.6
            }
        }
        
### Update pet reading [PUT]

A user may not be able to update a reading if it is taken 30seconds + after creation

+ Request

    + Headers
    
            X-Authorization: <token>
            
    + Body
    
            {
                "temperature": 37.6
            }

+ Parameters
    + pet_id
    + id
    
+ Response 200 (application/json)

        {
            "error": false,
            "result": {
                "id": 40,
                "pet_id": 14,
                "temperature": 37.6
            }
        }
        
        
## api.pet.{pet_id}.reading.assign [/api/pet/{pet_id}/reading/assign]
### Assign a microchip to a pet [POST]

+ Request

    + Headers
    
            X-Authorization: <token>
            
    + Body
    
            {
                "pet_id": 1
            }
            
+ Response 201 (application/json)

        {
          "error": false,
          "result": "Pet microchip number assigned"
        }



## api.pet.{pet_id}.reading.{reading_id}.symptom [/api/pet/{pet_id}/reading/{reading_id}/symptom]

### Get all symptoms of a reading [GET]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Response 201 (application/json)

        {
            "error": false,
            "result": [
                {
                    "0":  {
                        "id": 8,
                        "reading_id": 40,
                        "symptom_id": 3,
                        "updated_at": "2015-02-18 11:49:36",
                        "created_at": "2015-02-17 15:24:30"
                    }
                }
            ]
        }

### Add a symptom to a reading [POST]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Request (application/json)
            
        {
            "symptom_id": 5
        }

+ Response 201 (application/json)

        {
            "error": false,
            "result": {
                "symptom_id": "5",
                "reading_id": 40,
            }
        }
        
## api.pet.{pet_id}.reading.{reading_id}.symptom.{id} [/api/pet/{pet_id}/reading/{reading_id}/symptom/{id}]

### Get reading symptom by id [GET]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + pet_id
    + reading_id
    + id
    
+ Response 200 (application/json)

        {
            "error": false,
            "result": {
                "reading_id": 40,
                "symptom_id": 5,
                "updated_at": "2015-02-17 15:24:30",
                "created_at": "2015-02-17 15:24:30"
            }
        }
        

### Delete reading symptom [DELETE]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + pet_id
    + reading_id
    + id
    
+ Response 200 (application/json)

        {
            "error": false
        }
       
## api.pet.{pet_id}.vet [/api/pet/{pet_id}/vet]
### Get vets for a specific pet [GET]
+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + pet_id
    
+ Response 200 (application/json)

        {
            "error": false,
            "result": [
                {
                "vet_id": 1,
                "pet_id": 1,
                "approved": 0
                }
            ] 
        }
       
### Assign a vet to a pet [POST]
+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + pet_id
    
+ Request (application/json)
            
        {
            "vet_id":   1,
            "approved": 1
        }

+ Response 201 (application/json)

        {
            "error": false,
            "result": {
                "vet_id": 2,
                "pet_id": "4"
            }
        }
       
## api.pet.{pet_id}.vet.{vet_id} [/api/pet/{pet_id}/vet/{vet_id}]
### Dissociate a vet from a pet [DELETE]
+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + pet_id
    + vet_id
    
+ Response 200 (application/json)

        {
            "error": false
        }
        
        
## api.vet.search.all [/api/vet/search/all]

### Search for all vets [GET]

+ Response 200 (application/json)

        {
            "error": false,
            "result": [
                {
                  "id": 1,
                  "company_name": "066 Veterinary Centre Ltd",
                  "contact_name": "Vet McVetison",
                  "email": "mcvetison@iownallthevets.com",
                  "fax": "012345678910",
                  "telephone": "01424 839010",
                  "address_1": "100 Dummy Street",
                  "address_2": "Fake lane",
                  "city": "Somerset",
                  "county": "Vetishire",
                  "zip": "CB500TV",
                  "units": null,
                  "latitude": "51.2079451",
                  "longitude": "-2.6506662",
                  "photo_id": null,
                  "created_at": "2015-05-27 13:52:13",
                  "updated_at": "2015-05-28 10:12:27",
                  "confirmed": null,
                  "remember_token": null
                },
                {
                  "id": 2,
                  "company_name": "4 Paws Vets",
                  "contact_name": "Vet McVetison",
                  "email": "mcvetison@iownallthevets.com",
                  "fax": "012345678910",
                  "telephone": "0208 540 7275",
                  "address_1": "100 Dummy Street",
                  "address_2": "Fake lane",
                  "city": "London",
                  "county": "Vetishire",
                  "zip": "CB500TV",
                  "units": null,
                  "latitude": "51.5073509",
                  "longitude": "-0.1277583",
                  "photo_id": null,
                  "created_at": "2015-05-27 13:52:13",
                  "updated_at": "2015-05-28 10:12:27",
                  "confirmed": null,
                  "remember_token": null
                },
                {
                  "id": 3,
                  "company_name": "608 Veterinary Group",
                  "contact_name": "Vet McVetison",
                  "email": "mcvetison@iownallthevets.com",
                  "fax": "012345678910",
                  "telephone": "0121 7053044",
                  "address_1": "100 Dummy Street",
                  "address_2": "Fake lane",
                  "city": "West Midlands",
                  "county": "Vetishire",
                  "zip": "CB500TV",
                  "units": null,
                  "latitude": "52.3836607",
                  "longitude": "-1.7561314",
                  "photo_id": null,
                  "created_at": "2015-05-27 13:52:13",
                  "updated_at": "2015-05-28 10:12:27",
                  "confirmed": null,
                  "remember_token": null
                }
            ]
        }

## api.vet.search.name [/api/vet/search/name]

### Search for vets by name [POST]

+ Request (application/json)
            
        {
            "term": "acti"
        }


+ Response 200 (application/json)

        {
          "error": false,
          "result": [
                {
                  "id": 54,
                  "company_name": "Archway Vet Practice (S.Cumbria) Ltd",
                  "contact_name": "Vet McVetison",
                  "email": "mcvetison@iownallthevets.com",
                  "fax": "012345678910",
                  "telephone": "01539 532669",
                  "address_1": "100 Dummy Street",
                  "address_2": "Fake lane",
                  "city": "Cumbria",
                  "county": "Vetishire",
                  "zip": "CB500TV",
                  "units": null,
                  "latitude": "54.5772323",
                  "longitude": "-2.7974835",
                  "photo_id": null,
                  "created_at": "2015-05-27 13:52:13",
                  "updated_at": "2015-05-28 10:12:27",
                  "confirmed": null,
                  "remember_token": null
                },
                {
                  "id": 55,
                  "company_name": "Archway Vet Practice Ltd",
                  "contact_name": "Vet McVetison",
                  "email": "mcvetison@iownallthevets.com",
                  "fax": "012345678910",
                  "telephone": "01730 262101",
                  "address_1": "100 Dummy Street",
                  "address_2": "Fake lane",
                  "city": "Hampshire",
                  "county": "Vetishire",
                  "zip": "CB500TV",
                  "units": null,
                  "latitude": "51.0895203",
                  "longitude": "-1.216844",
                  "photo_id": null,
                  "created_at": "2015-05-27 13:52:13",
                  "updated_at": "2015-05-28 10:12:27",
                  "confirmed": null,
                  "remember_token": null
                },
            ]
        }
        
## api.vet.search.location [/api/vet/search/location]

### Search for vets by location [POST]

+ Request (application/json)
            
        {
            "location": "leicester"
            "distance" : "5"
        }


+ Response 200 (application/json)

        {
          "error": false,
          "result": [
            {
              "id": 136,
              "company_name": "Best Friends Group - Leicester",
              "contact_name": "Vet McVetison",
              "email": "mcvetison@iownallthevets.com",
              "fax": "012345678910",
              "telephone": "0116 2517677",
              "address_1": "100 Dummy Street",
              "address_2": "Fake lane",
              "city": "Leicestershire",
              "county": "Vetishire",
              "zip": "CB500TV",
              "units": null,
              "latitude": "52.6368778",
              "longitude": "-1.1397592",
              "photo_id": null,
              "created_at": "2015-05-27 13:52:13",
              "updated_at": "2015-05-28 10:12:27",
              "confirmed": null,
              "remember_token": null,
              "distance": 0
            }
          ]
        }
        

## api.user.photo [/api/user/photo]

### Send User Photo Info [POST]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Request (multipart/form-data)
        
        "image_path": img 
        "title" : "testing"
    
+ Response 200 (application/json)

        {
            "error": false,
            "result": {
                "id": 2,
                "first_name": "John",
                "last_name": "Doe",
                "email": "j.doe@sureflap.com",
                "provider": null,
                "provider_id": null,
                "photo_id": 2,
                "telephone": "01223432654",
                "units": null,
                "weight_units": null,
                "created_at": "2016-01-27 08:17:17",
                "updated_at": "2016-01-28 13:48:13",
                "remember_token": null,
                "confirmed": null
            }
        }

## api.pet.{pet_id}.photo [/api/pet/{pet_id}/photo]

### Send Pet Photo Info [POST]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + pet_id

+ Request (multipart/form-data)
        
        "image_path": img 
        "title" : "testing"
    
+ Response 200 (application/json)

        {
          "error": false,
          "result": {
            "id": 4,
            "name": "Milly Mii",
            "microchip_number": "5746352413",
            "breed_id": null,
            "breed_wildcard": null,
            "photo_id": 4,
            "date_of_birth": "2012-12-12",
            "weight": "5",
            "gender": 0,
            "vet_id": null,
            "user_id": 2,
            "created_at": "2016-01-27 10:16:44",
            "updated_at": "2016-01-28 14:10:00"
          }
        }


## api.photo.{photo_id} [/api/photo/{photo_id}]

### Get a Photo Info [GET]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + photo_id

+ Response 200 (application/json)

        {
            "error": false,
            "result": {
                "id": 4,
                "title": "2",
                "location": "uploads/users/2/GWLbmjyl6OzxoAQ2wu2xl8ubwRCrjGeMoqkS8ZWkDiDz7HeNMIwH9V3CcWmclYtmLo1TZI7BgNmSjIcUwJw.png",
                "uploading_user_id": 2,
                "uploading_vet_id": null,
                "created_at": "2016-01-28 14:10:00",
                "updated_at": "2016-01-28 14:10:00"
            }
        }


## api.auth.{provider}.login [/api/auth/{provider}/login]

### Login from external providers [GET]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + provider
    
+ Request (application/json)
            
        {
            "email":"juanstan@gmail.com",
            "id":1679215355651823,
            "first_name": "Juan",
            "last_name": "Piqueras Acevedo",
            "provider":"facebook"
        
        }

+ Response 200 (application/json)

        {
            "error": false,
            "result": {
                "token": {
                "token": "$2y$10$14sN72fbyR9Fdz4.hwIBh.yO31DbBkVZyY18eZtmcLUWRU9E.7CUS",
                "expires_at": "2016-02-04 15:32:45",
                "created_at": "2016-01-28 15:32:46"
                },
                "user": {
                    "first_name": "Juan",
                    "last_name": "Piqueras Acevedo",
                    "email": "juanstan@gmail.com",
                    "provider": "facebook",
                    "provider_id": 1679215355651800,
                    "units": 0,
                    "weight_units": 0,
                    "updated_at": "2016-01-28 15:31:57",
                    "created_at": "2016-01-28 15:31:57",
                    "id": 4
                }
            }
        }

## api.password.reset [/api/password/reset]
### request to reset the password [GET]

+ Request (application/json)
            
        {
            "email":"juanstan@gmail.com"
        }

+ Response 200 (application/json)

        {
          "error": false,
          "result": "Your request to reset your password has been accepted, we have sent further details to your email address"
        }


# Group Vet

## api.vet [/api/vet]

### Get all registered vet [GET]

+ Response 200 (application/json)

        {
            "error": false,
            "result": [
                {
                    "0":  {
                        "id": 4,
                        "company_name": "local vet",
                        "contact_name": "Axel Hunter",
                        "email_address": "a.hunter@sureflap.co.uk",
                        "telephone": "134578781234",
                        "address_1": "340 main street",
                        "address_2": "",
                        "city": "Venice",
                        "state": "CA",
                        "county": "",
                        "zip": "90291",
                        "latitude": null,
                        "longitude": null,
                        "image_path": null,
                        "created_at": "2015-02-10 14:29:36",
                        "updated_at": "2015-02-10 14:29:36"
                    },
                    "1":  {
                        "id": 6,
                        "company_name": "Tatooine Veterinary",
                        "contact_name": "Jeff Vader",
                        "email_address": "j.vader@sureflap.co.uk",
                        "telephone": "134578781234",
                        "address_1": "341 main street",
                        "address_2": "",
                        "city": "Venice",
                        "state": "CA",
                        "county": "",
                        "zip": "90291",
                        "latitude": null,
                        "longitude": null,
                        "image_path": null,
                        "created_at": "2015-02-10 15:08:43",
                        "updated_at": "2015-02-19 12:13:54"
                    },
                    "2":  {
                        "id": 7,
                        "company_name": "Cambridge Veterinary",
                        "contact_name": "Jenifer Flaps",
                        "email_address": "jflaps@cveterinary.com",
                        "telephone": "01223123098",
                        "address_1": "15 High Street",
                        "address_2": null,
                        "city": "Cambridge",
                        "state": null,
                        "county": "Cambridgeshire",
                        "zip": "CB3",
                        "latitude": null,
                        "longitude": null,
                        "image_path": "vet_image.jpg",
                        "created_at": "2015-02-19 09:51:49",
                        "updated_at": "2015-02-19 09:51:49"
                    }
                }
            ]
        }

### Create a vet account [POST]

Get the basic information needed to create an account.

+ Request (application/json)
            
        {
            "company_name": "Cambridge Veterinary",
            "contact_name": "Jenifer Flaps",
            "email_address": "jflaps@cveterinary.com",
            "telephone": "01223123098",
            "address_1": "15 High Street",
            "city": "Cambridge",
            "county": "Cambridgeshire",
            "zip": "CB3",
            "image_path": "vet_image.jpg",
            "password": "changme"
        }

+ Response 201 (application/json)

        {
            "error": false,
            "result": {
                "company_name": "Cambridge Veterinary",
                "contact_name": "Jenifer Flaps",
                "email_address": "jflaps@cveterinary.com",
                "telephone": "01223123098",
                "address_1": "15 High Street",
                "city": "Cambridge",
                "county": "Cambridgeshire",
                "zip": "CB3",
                "image_path": "vet_image.jpg",
                "updated_at": "2015-02-19 09:51:49",
                "created_at": "2015-02-19 09:51:49",
                "id": 7
            }
        }

## api.vet.{id} [/api/vet/{id}]

### Get information on vet account [GET]
            
+ Parameters
    + id

+ Response 200 (application/json)

        {
            "error": false,
            "result": {
                "id": 6,
                "company_name": "The other vet",
                "contact_name": "Jeff Vader",
                "email_address": "j.vader@sureflap.co.uk",
                "telephone": "134578781234",
                "address_1": "341 main street",
                "address_2": "",
                "city": "Venice",
                "state": "CA",
                "county": "",
                "zip": "90291",
                "latitude": null,
                "longitude": null,
                "image_path": null,
                "created_at": "2015-02-10 15:08:43",
                "updated_at": "2015-02-10 15:08:43"
            }
        }
        
### Update vet account [PUT]

+ Request

    + Headers
    
            X-Authorization: <token>
            
    + Body
    
            {
                "company_name": "Tatooine Veterinary"
            }

+ Parameters
    + id
    
+ Response 200 (application/json)

        {
            "error": false,
            "result": {
                "id": 6,
                "company_name": "Tatooine Veterinary",
                "contact_name": "Jeff Vader",
                "email_address": "j.vader@sureflap.co.uk",
                "telephone": "134578781234",
                "address_1": "341 main street",
                "address_2": "",
                "city": "Venice",
                "state": "CA",
                "county": "",
                "zip": "90291",
                "latitude": null,
                "longitude": null,
                "image_path": null,
                "created_at": "2015-02-10 15:08:43",
                "updated_at": "2015-02-19 12:13:54"
            }
        }
        
### Delete vet account [DELETE]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + id
    
+ Response 200 (application/json)

        {
            "error": false
        }
        

## api.vet.login [/api/vet/login]

### Attempt vet login [POST]

You can use this method to authenticate a user with a valid email and password. This will in turn generate a token.

+ Request (application/json)

    + Headers
    
    + Body
            
            {
                "email_address": "j.vader@sureflap.co.uk",
                "password": "changeme"
            }

+ Response 200 (application/json)

        {
            "error": false,
            "result": {
                "token": {
                    "token": "$2y$10$veM/K8hP0pAxHEf4Ov9rGepvgGb0VyZJJF4xeRpbhF6VK/rZhmEqe",
                    "expires_at": "2015-02-26 09:39:53",
                    "created_at": "2015-02-19 09:39:53"
                },
                "user": {
                    "id": 6,
                    "company_name": "The other vet",
                    "contact_name": "Jeff Vader",
                    "email_address": "j.vader@sureflap.co.uk",
                    "telephone": "134578781234",
                    "address_1": "341 main street",
                    "address_2": "",
                    "city": "Venice",
                    "state": "CA",
                    "county": "",
                    "zip": "90291",
                    "latitude": null,
                    "longitude": null,
                    "image_path": null,
                    "created_at": "2015-02-10 15:08:43",
                    "updated_at": "2015-02-10 15:08:43"
                }
            }
        }
        
## api.vet.logout [/api/vet/logout]

### Attempt vet logout [POST]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Response 201 (application/json)

            {
                "error": false,
                "message": "You are now logged out"
            }
        
## api.vet.animal [/api/vet/animal]

### Get all animals on account [GET]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Response 201 (application/json)

        {
            "error": false,
            "result": [
                {
                    "0":  {
                        "id": 9,
                        "name": "Robyn",
                        "microchip_number": "123456",
                        "breed": "Great Dane",
                        "date_of_birth": null,
                        "weight": 50,
                        "size": "M",
                        "gender": "Male",
                        "image_path": null,
                        "user_id": 14,
                        "pivot": {
                            "vet_id": 4,
                            "animal_id": 9,
                            "created_at": "2015-02-16 11:12:46",
                            "updated_at": "2015-02-16 11:12:46"
                        }
                    },
                    "1":  {
                        "id": 14,
                        "name": "Milly Mii",
                        "microchip_number": "1234555555",
                        "breed": "Chihuahua",
                        "date_of_birth": "2012-12-13",
                        "weight": 4.7,
                        "size": "s",
                        "gender": "Female",
                        "image_path": "mydog2.jpg",
                        "user_id": 16,
                        "pivot": {
                            "vet_id": 4,
                            "animal_id": 14,
                            "created_at": "2015-02-18 16:16:07",
                            "updated_at": "2015-02-18 16:20:51"
                        }
                    }
                }
            ]
        }

## api.vet.animal.{id} [/api/vet/animal/{id}]
        
### Get animal on account [GET]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Parameters
    + id
    
+ Response 200 (application/json)

        {
            "error": false,
            "result": {
                "id": 14,
                "name": "Milly Mii",
                "microchip_number": "1234555555",
                "breed": "Chihuahua",
                "date_of_birth": "2012-12-13",
                "weight": 4.7,
                "size": "s",
                "gender": "Female",
                "image_path": "mydog2.jpg",
                "user_id": 16,
                "vet_id": 4,
                "animal_id": 14,
                "approved": 1,
                "request_type": 1,
                "request_reason": "Vet checkup",
                "response_reason": "approved",
                "expiry_type": null,
                "expiry_days": null,
                "approval_date": null,
                "expiry_date": null
            }
        }
        
## api.vet.animal.{animal_id}.reading [/api/vet/animal/{animal_id}/reading]

### Get all readings for animal [GET]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Response 201 (application/json)

        {
            "error": false,
            "result": [
                {
                    "0":  {
                        "id": 34,
                        "animal_id": 14,
                        "temperature": 37.5,
                        "device_id": null
                    },
                    "1":  {
                        "id": 35,
                        "animal_id": 14,
                        "temperature": 37.7,
                        "device_id": null
                    },
                    "2":  {
                        "id": 36,
                        "animal_id": 14,
                        "temperature": 37.6,
                        "device_id": null
                    },
                    "3":  {
                        "id": 37,
                        "animal_id": 14,
                        "temperature": 37.5,
                        "device_id": null
                    },
                    "4":  {
                        "id": 38,
                        "animal_id": 14,
                        "temperature": 37.6,
                        "device_id": null
                    },
                    "5":  {
                        "id": 39,
                        "animal_id": 14,
                        "temperature": 37.8,
                        "device_id": null
                    },
                    "6":  {
                        "id": 40,
                        "animal_id": 14,
                        "temperature": 37.6,
                        "device_id": null
                    }
                }
            ]
        }
        
## api.vet.animal.{animal_id}.reading [/api/vet/animal/{animal_id}/reading/{id}]

### Get specific reading for animal [GET]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Response 201 (application/json)

        {
            "error": false,
            "result": {
                "id": 35,
                "animal_id": 14,
                "temperature": 37.7,
                "reading_id": null
            }
        }

## api.vet.animal.{animal_id}.reading [/api/vet/animal/{animal_id}/reading/{id}/symptom]

### Get symptoms for animal reading [GET]

+ Request

    + Headers
    
            X-Authorization: <token>

+ Response 201 (application/json)

        {
            "error": false,
            "result": [
                {
                    "0":  {
                        "id": 6,
                        "reading_id": 40,
                        "symptom_id": 15,
                        "updated_at": "2015-02-16 09:18:40",
                        "created_at": "2015-02-16 09:18:40"
                    },
                    "1":  {
                        "id": 7,
                        "reading_id": 40,
                        "symptom_id": 12,
                        "updated_at": "2015-02-17 09:11:10",
                        "created_at": "2015-02-17 09:11:10"
                    },
                    "2":  {
                        "id": 8,
                        "reading_id": 40,
                        "symptom_id": 3,
                        "updated_at": "2015-02-18 11:49:36",
                        "created_at": "2015-02-17 15:24:30"
                    }
                }
            ]
        }
        

# Group Other Items

## api.breeds [/api/breeds]

### Get all breeds [GET]

+ Response 200 (application/json)

        {
            "error": false,
            "result": [
                {
                    "id": 1,
                    "name": "Affenpinscher",
                    "size": "S"
                },
                {
                    "id": 2,
                    "name": "Afghan Hound",
                    "size": "L"
                }
            ]
        }

## api.symptoms [/api/symptoms]

### Get all symptoms [GET]

+ Response 200 (application/json)

        {
            "error": false,
            "result": [
                {
                    "id": 1,
                    "name": "All looks normal"
                },
                {
                    "id": 2,
                    "name": "Itching/Scratching"
                },
                {
                    "id": 3,
                    "name": "Hair Loss"
                },
                {
                    "id": 4,
                    "name": "Diarrhea"
                }
            ]
        }

## api.conditions [/api/conditions]

### Get all conditions [GET]

+ Response 200 (application/json)

        {
            "error": false,
            "result": [
                {
                "id": 1,
                "name": "Allergic Dermatitis or other Skin Condition"
                },
                {
                "id": 2,
                "name": "Arthritis and Joint Pain"
                },
                {
                "id": 3,
                "name": "Behavioral Changes & Alertness Changes"
                },
                {
                "id": 4,
                "name": "Cancer"
                }
            ]
        }
