<?php

class DatabaseSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		Eloquent::unguard();

		$this->call('SymtomTableSeeder');
        $this->call('BreedTableSeeder');
	}

}

class SymtomTableSeeder extends Seeder {

    public function run()
    {
        DB::table('symptoms')->delete();

        DB::table('symptoms')->insert(array(
            array('name'=>'Exercise Intolerance'),
            array('name'=>'Difficulty Walking/rising/jumping'),
            array('name'=>'Enlarged Lymph Nodes'),
            array('name'=>'Exercise Intolerance'),
            array('name'=>'Fever'),
            array('name'=>'Itching/scratching'),
            array('name'=>'Limping'),
            array('name'=>'Muscle Atrophy'),
            array('name'=>'Pain'),
            array('name'=>'Shaking'),
            array('name'=>'Stiffness'),
            array('name'=>'Swelling'),
        ));
    }

}

class BreedTableSeeder extends Seeder {

    public function run()
    {
        DB::table('breeds')->delete();

        DB::table('breeds')->insert(array(
            array('name'=>'Akbash'),
            array('name'=>'Alaskan Klee Kai'),
            array('name'=>'Appenzeller Sennenhunde'),
            array('name'=>'Australian Cattle Dog'),
            array('name'=>'Australian Shepherd'),
            array('name'=>'Bearded Collie'),
            array('name'=>'Beauceron'),
            array('name'=>'Belgian Groenendael'),
            array('name'=>'Belgian Malinois'),
            array('name'=>'Belgian Tervuren'),
            array('name'=>'Border Collie'),
            array('name'=>'Bouvier des Flandres'),
            array('name'=>'Briard'),
            array('name'=>'Canaan Dog'),
            array('name'=>'Cardigan Welsh Corgi'),
            array('name'=>'Carpathian Sheepdog'),
            array('name'=>'Catahoula Leopard Dog'),
            array('name'=>'Caucasian Mountain Dog'),
            array('name'=>'Central Anatolian Shepherd Dog'),
            array('name'=>'Central Asian Shepherd Dog'),
            array('name'=>'Czechoslovakian Wolfdog'),
            array('name'=>'Dutch Shepherd'),
            array('name'=>'English Shepherd'),
            array('name'=>'Entlebucher Mountain Dog'),
            array('name'=>'Estrela Mountain Dog'),
            array('name'=>'Finnish Lapphund'),
            array('name'=>'German Shepherd Dog'),
            array('name'=>'Hovawart'),
            array('name'=>'Icelandic Sheepdog'),
            array('name'=>'Kangal'),
            array('name'=>'Karelian Bear Dog'),
            array('name'=>'Lancashire Heeler'),
            array('name'=>'Lapponian Herder'),
            array('name'=>'Mudi'),
            array('name'=>'Norwegian Buhund'),
            array('name'=>'Old English Sheepdog'),
            array('name'=>'Pembroke Welsh Corgi'),
            array('name'=>'Polish Lowland Sheepdog'),
            array('name'=>'Portuguese sheepdog'),
            array('name'=>'Puli'),
            array('name'=>'Pyrenean Shepherd'),
            array('name'=>'Rough Collie'),
            array('name'=>'Schapendoes'),
            array('name'=>'Shetland Sheepdog'),
            array('name'=>'Smooth Collie'),
            array('name'=>'Swedish Vallhund'),
            array('name'=>'Turkish Tazi'),
            array('name'=>'Welsh Sheepdog'),
            array('name'=>'White Shepherd'),
            array('name'=>'Yugoslavian Shepherd Dog-Sarplaninac'),
            array('name'=>'Afghan Hound'),
            array('name'=>'American English Coonhound'),
            array('name'=>'American Foxhound'),
            array('name'=>'Basenji'),
            array('name'=>'Basset Hound'),
            array('name'=>'Beagle'),
            array('name'=>'Black and Tan Coonhound'),
            array('name'=>'Bloodhound'),
            array('name'=>'Bluetick Coonhound'),
            array('name'=>'Borzoi'),
            array('name'=>'Dachshund'),
            array('name'=>'English Coonhound'),
            array('name'=>'English Foxhound'),
            array('name'=>'Galgo Español'),
            array('name'=>'Greyhound'),
            array('name'=>'Harrier'),
            array('name'=>'Hortaya borzaya'),
            array('name'=>'Ibizan Hound'),
            array('name'=>'Irish Wolfhound'),
            array('name'=>'Norman Artesian Basset'),
            array('name'=>'Norwegian Elkhound'),
            array('name'=>'Otterhound'),
            array('name'=>'Petit Basset Griffon Vendéen'),
            array('name'=>'Pharaoh Hound'),
            array('name'=>'Plott Hound'),
            array('name'=>'Redbone Coonhound'),
            array('name'=>'Rhodesian Ridgeback'),
            array('name'=>'Saluki'),
            array('name'=>'Scottish Deerhound'),
            array('name'=>'Treeing Walker Coonhound'),
            array('name'=>'Whippet'),
            array('name'=>'Andalusian Podenco'),
            array('name'=>'Bracco Italiano'),
            array('name'=>'Grand Griffon Vendeen'),
            array('name'=>'Kishu Ken'),
            array('name'=>'Portuguese Pointer'),
            array('name'=>'Rastreador Brasileiro'),
            array('name'=>'Small Munsterlander Pointer'),
            array('name'=>'Thai Ridgeback'),
            array('name'=>'Treeing Tennessee Brindle'),
            array('name'=>'African Boerboel'),
            array('name'=>'Ca de Bou'),
            array('name'=>'Mastín Español'),
            array('name'=>'Mastín del Pirineo'),
            array('name'=>'Olde English Bulldogge'),
            array('name'=>'Perro de Presa Canario'),
            array('name'=>'Rafeiro do Alentejo'),
            array('name'=>'Staffordshire Bull Terrier'),
            array('name'=>'Tosa'),
            array('name'=>'Argentine Dogo'),
            array('name'=>'Azawakh'),
            array('name'=>'Belgian Laekenois'),
            array('name'=>'Bergamasco'),
            array('name'=>'Chinook'),
            array('name'=>'Coton de Tulear'),
            array('name'=>'Hungarian Wirehaired Vizsla'),
            array('name'=>'Peruvian Inca Orchid'),
            array('name'=>'Portuguese Podengo'),
            array('name'=>'Pumi'),
            array('name'=>'Sloughi'),
            array('name'=>'Spanish Water Dog'),
            array('name'=>'Alapaha Blue Blood Bulldog'),
            array('name'=>'American Bulldog'),
            array('name'=>'American Eskimo Dog'),
            array('name'=>'Bichon Frise'),
            array('name'=>'Boston Terrier'),
            array('name'=>'Bulldog'),
            array('name'=>'Chow Chow'),
            array('name'=>'Dalmatian'),
            array('name'=>'Finnish Spitz'),
            array('name'=>'French Bulldog'),
            array('name'=>'German Spitz'),
            array('name'=>'Keeshond'),
            array('name'=>'Lhasa Apso'),
            array('name'=>'Löwchen'),
            array('name'=>'Norwegian Lundehund'),
            array('name'=>'Poodle'),
            array('name'=>'Schipperke'),
            array('name'=>'Shar-Pei'),
            array('name'=>'Shiba Inu'),
            array('name'=>'Tibetan Spaniel'),
            array('name'=>'Tibetan Terrier'),
            array('name'=>'Xoloitzcuintli'),
            array('name'=>'Kai Ken'),
            array('name'=>'American Cocker Spaniel'),
            array('name'=>'American Water Spaniel'),
            array('name'=>'Boykin Spaniel'),
            array('name'=>'Brittany'),
            array('name'=>'Chesapeake Bay Retriever'),
            array('name'=>'Clumber Spaniel'),
            array('name'=>'Curly Coated Retriever'),
            array('name'=>'English Cocker Spaniel'),
            array('name'=>'English Setter'),
            array('name'=>'English Springer Spaniel'),
            array('name'=>'Field Spaniel'),
            array('name'=>'Flat-Coated Retriever'),
            array('name'=>'German Shorthaired Pointer'),
            array('name'=>'German Wirehaired Pointer'),
            array('name'=>'Golden Retriever'),
            array('name'=>'Gordon Setter'),
            array('name'=>'Hungarian Vizsla'),
            array('name'=>'Irish Red and White Setter'),
            array('name'=>'Irish Setter'),
            array('name'=>'Irish Water Spaniel'),
            array('name'=>'Kooikerhondje'),
            array('name'=>'Labrador Retriever'),
            array('name'=>'Lagotto Romagnolo'),
            array('name'=>'Nova Scotia Duck Tolling Retriever'),
            array('name'=>'Pointer'),
            array('name'=>'Spinone Italiano'),
            array('name'=>'Stabyhoun'),
            array('name'=>'Sussex Spaniel'),
            array('name'=>'Weimaraner'),
            array('name'=>'Welsh Springer Spaniel'),
            array('name'=>'Wirehaired Pointing Griffon'),
            array('name'=>'Airedale Terrier'),
            array('name'=>'American Pit Bull Terrier'),
            array('name'=>'American Staffordshire Terrier'),
            array('name'=>'Australian Terrier'),
            array('name'=>'Bedlington Terrier'),
            array('name'=>'Bodeguero Andaluz'),
            array('name'=>'Border Terrier'),
            array('name'=>'Bull Terrier'),
            array('name'=>'Cairn Terrier'),
            array('name'=>'Cesky Terrier'),
            array('name'=>'Dandie Dinmont Terrier'),
            array('name'=>'Glen of Imaal Terrier'),
            array('name'=>'Irish Terrier'),
            array('name'=>'Jack Russell Terrier'),
            array('name'=>'Kerry Blue Terrier'),
            array('name'=>'Lakeland Terrier'),
            array('name'=>'Manchester Terrier'),
            array('name'=>'Miniature Bull Terrier'),
            array('name'=>'Miniature Schnauzer'),
            array('name'=>'Norfolk Terrier'),
            array('name'=>'Norwich Terrier'),
            array('name'=>'Parson Russell Terrier'),
            array('name'=>'Rat Terrier'),
            array('name'=>'Rater Valenciá'),
            array('name'=>'Scottish Terrier'),
            array('name'=>'Sealyham Terrier'),
            array('name'=>'Skye Terrier'),
            array('name'=>'Smooth Fox Terrier'),
            array('name'=>'Soft Coated Wheaten Terrier'),
            array('name'=>'Welsh Terrier'),
            array('name'=>'West Highland White Terrier'),
            array('name'=>'Wire Fox Terrier'),
            array('name'=>'Affenpinscher'),
            array('name'=>'Biewer Yorkshire a la Pom-Pon'),
            array('name'=>'Bolognese'),
            array('name'=>'Brussels Griffon'),
            array('name'=>'Cavalier King Charles Spaniel'),
            array('name'=>'Chihuahua'),
            array('name'=>'Chinese Crested'),
            array('name'=>'English Toy Spaniel'),
            array('name'=>'Havanese'),
            array('name'=>'Italian Greyhound'),
            array('name'=>'Japanese Chin'),
            array('name'=>'Maltese'),
            array('name'=>'Miniature Pinscher'),
            array('name'=>'Papillon'),
            array('name'=>'Pekingese'),
            array('name'=>'Pomeranian'),
            array('name'=>'Pug'),
            array('name'=>'Shih Tzu'),
            array('name'=>'Silky Terrier'),
            array('name'=>'Toy Fox Terrier'),
            array('name'=>'Yorkshire Terrier'),
            array('name'=>'Akita'),
            array('name'=>'Alaskan Malamute'),
            array('name'=>'Anatolian Shepherd Dog'),
            array('name'=>'Bernese Mountain Dog'),
            array('name'=>'Black Russian Terrier'),
            array('name'=>'Boxer'),
            array('name'=>'Bullmastiff'),
            array('name'=>'Cane Corso'),
            array('name'=>'Doberman Pinscher'),
            array('name'=>'Dogue de Bordeaux'),
            array('name'=>'Fila Brasileiro'),
            array('name'=>'German Pinscher'),
            array('name'=>'Giant Schnauzer'),
            array('name'=>'Great Dane'),
            array('name'=>'Great Pyrenees'),
            array('name'=>'Greater Swiss Mountain Dog'),
            array('name'=>'Komondor'),
            array('name'=>'Kuvasz'),
            array('name'=>'Leonberger'),
            array('name'=>'Mastiff'),
            array('name'=>'Neapolitan Mastiff'),
            array('name'=>'Newfoundland'),
            array('name'=>'Portuguese Water Dog'),
            array('name'=>'Rottweiler'),
            array('name'=>'Saint Bernard'),
            array('name'=>'Samoyed'),
            array('name'=>'Siberian Husky'),
            array('name'=>'Standard Schnauzer'),
            array('name'=>'Tibetan Mastiff'),
        ));
    }

}
