<?php

class DatabaseSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		Eloquent::unguard();

		$this->call('SymtomTableSeeder');
        $this->call('ConditionTableSeeder');
        $this->call('BreedTableSeeder');
	}

}

class SymtomTableSeeder extends Seeder {

    public function run()
    {
        DB::table('symptoms')->delete();

        DB::table('symptoms')->insert(array(
            array('name'=>'All looks normal'),
            array('name'=>'Itching/Scratching'),
            array('name'=>'Hair Loss'),
            array('name'=>'Diarrhea'),
            array('name'=>'Vomiting'),
            array('name'=>'Drooling'),
            array('name'=>'Urinating a lot or Urine loss'),
            array('name'=>'Restless'),
            array('name'=>'Changed appetite'),
            array('name'=>'Increased eating / Abnormal eating'),
            array('name'=>'Increased head shaking'),
            array('name'=>'Change in odor'),
            array('name'=>'Weight loss'),
            array('name'=>'Abnormal behavior'),
            array('name'=>'Not playful'),
            array('name'=>'Abnormal movement'),
            array('name'=>'Limping'),
            array('name'=>'Overall poor appearance'),
            array('name'=>'Dull Coat'),
            array('name'=>'Drinking a lot'),
            array('name'=>'Bleeding'),
            array('name'=>'Looks pale'),
            array('name'=>'Change in bark'),
        ));
    }

}

class ConditionTableSeeder extends Seeder {

    public function run()
    {
        DB::table('conditions')->delete();

        DB::table('conditions')->insert(array(
            array('name'=>'None'),
            array('name'=>'Allergic Dermatitis or other Skin Condition'),
            array('name'=>'Arthritis and Joint Pain'),
            array('name'=>'Behavioral Changes & Alertness Changes'),
            array('name'=>'Cancer'),
            array('name'=>'Dental Disease'),
            array('name'=>'Diabetes Mellitus'),
            array('name'=>'Hypothyroidism'),
            array('name'=>'Cushing’s Syndrome'),
            array('name'=>'Addison’s Disease'),
            array('name'=>'Food Allergy or Food Intolerance'),
            array('name'=>'Gastrointestinal or Digestive Disorder'),
            array('name'=>'Heart Disease'),
            array('name'=>'Kidney Disease'),
            array('name'=>'Liver Disease'),
            array('name'=>'Urinary Bladder Stones'),
            array('name'=>'Incontinence'),
            array('name'=>'Previous Accident'),
            array('name'=>'Recent Surgery'),
            array('name'=>') Nervous System Disorder'),
            array('name'=>'Bone or Muscular Disorder'),
            array('name'=>'Eye Condition'),
            array('name'=>'Recurrent Ear infections'),
            array('name'=>'Tooth Problems'),
        ));
    }

}

class BreedTableSeeder extends Seeder {

    public function run()
    {
        DB::table('breeds')->delete();

        DB::table('breeds')->insert(array(
            array('name'=>'Affenpinscher','weight'=>'S'),
            array('name'=>'Afghan Hound','weight'=>'L'),
            array('name'=>'African Wild Dog','weight'=>'Ma'),
            array('name'=>'Africanis','weight'=>'M'),
            array('name'=>'Aidi','weight'=>'M'),
            array('name'=>'Airedale Terrier','weight'=>'S'),
            array('name'=>'Akbash Dog','weight'=>'L'),
            array('name'=>'Alano Espanol','weight'=>'L'),
            array('name'=>'Alapaha Blue Blood Bulldog','weight'=>'M'),
            array('name'=>'Alaskan Husky','weight'=>'L'),
            array('name'=>'Alaskan Klee Kai','weight'=>'M'),
            array('name'=>'Alaskan Malamute','weight'=>'L'),
            array('name'=>'Alopekis','weight'=>'S'),
            array('name'=>'American Akita','weight'=>'L'),
            array('name'=>'American Bulldog','weight'=>'L'),
            array('name'=>'American Cocker Spaniel','weight'=>'M'),
            array('name'=>'American Eskimo Dog','weight'=>'M'),
            array('name'=>'American Foxhound','weight'=>'L'),
            array('name'=>'American Hairless Terrier','weight'=>'S'),
            array('name'=>'American Mastiff','weight'=>'L'),
            array('name'=>'American Pit Bull Terrier','weight'=>'M'),
            array('name'=>'American Staffordshire Terrier','weight'=>'M'),
            array('name'=>'American Staghound','weight'=>'L'),
            array('name'=>'American Water Spaniel','weight'=>'M'),
            array('name'=>'American White Shepherd','weight'=>'M'),
            array('name'=>'Anatolian Shepherd Dog','weight'=>'L'),
            array('name'=>'Andalusian Hound','weight'=>'M'),
            array('name'=>'Appenzeller Sennenhund','weight'=>'M'),
            array('name'=>'Argentine Dogo','weight'=>'L'),
            array('name'=>'Ariege Pointer','weight'=>'L'),
            array('name'=>'Ariegeois','weight'=>'M'),
            array('name'=>'Australian Bulldog','weight'=>'M'),
            array('name'=>'Australian Cattle Dog','weight'=>'M'),
            array('name'=>'Australian Kelpie','weight'=>'M'),
            array('name'=>'Australian Shepherd','weight'=>'M'),
            array('name'=>'Australian Silky Terrier','weight'=>'S'),
            array('name'=>'Australian Stumpy Tail Cattle Dog','weight'=>'M'),
            array('name'=>'Australian Terrier','weight'=>'S'),
            array('name'=>'Austrian Black and Tan Hound','weight'=>'M'),
            array('name'=>'Austrian Pinscher','weight'=>'M'),
            array('name'=>'Azawakh','weight'=>'L'),
            array('name'=>'Barbet','weight'=>'M'),
            array('name'=>'Basenji','weight'=>'M'),
            array('name'=>'Basset Artesien Normand','weight'=>'S'),
            array('name'=>'Basset Bleu de Gascogne','weight'=>'S'),
            array('name'=>'Basset Fauve de Bretagne','weight'=>'S'),
            array('name'=>'Basset Hound','weight'=>'M'),
            array('name'=>'Bavarian Mountain Hound','weight'=>'M'),
            array('name'=>'Beagle','weight'=>'S'),
            array('name'=>'Beagle-Harrier','weight'=>'M'),
            array('name'=>'Beaglier','weight'=>'M'),
            array('name'=>'Bearded Collie','weight'=>'M'),
            array('name'=>'Beauceron','weight'=>'L'),
            array('name'=>'Bedlington Terrier','weight'=>'S'),
            array('name'=>'Belgian Shepherd Laekenois','weight'=>'M'),
            array('name'=>'Belgian Shepherd Malinois','weight'=>'M'),
            array('name'=>'Belgian Shepherd Tervuren','weight'=>'M'),
            array('name'=>'Bergamasco','weight'=>'M'),
            array('name'=>'Berger Picard','weight'=>'M'),
            array('name'=>'Bernese Mountain Dog','weight'=>'L'),
            array('name'=>'Bichon Frise','weight'=>'S'),
            array('name'=>'Black and Tan Coonhound','weight'=>'L'),
            array('name'=>'Black Norwegian Elkhound','weight'=>'S'),
            array('name'=>'Black Russian Terrier','weight'=>'L'),
            array('name'=>'Blackmouth Cur','weight'=>'M'),
            array('name'=>'Bloodhound','weight'=>'L'),
            array('name'=>'Blue Lacy','weight'=>'M'),
            array('name'=>'Blue Picardy Spaniel','weight'=>'L'),
            array('name'=>'Bluetick Coonhound','weight'=>'M'),
            array('name'=>'Boerboel','weight'=>'L'),
            array('name'=>'Bohemian Shepherd','weight'=>'M'),
            array('name'=>'Bolognese dog','weight'=>'S'),
            array('name'=>'Border Collie','weight'=>'M'),
            array('name'=>'Border Terrier','weight'=>'S'),
            array('name'=>'Borzoi','weight'=>'XL'),
            array('name'=>'Boston Terrier','weight'=>'S'),
            array('name'=>'Bouvier de Ardennes','weight'=>'M'),
            array('name'=>'Bouvier des Flanders','weight'=>'L'),
            array('name'=>'Boxer','weight'=>'M'),
            array('name'=>'Boykin Spaniel','weight'=>'M'),
            array('name'=>'Bracco Italiano','weight'=>'L'),
            array('name'=>'Braque du Bourbonnais','weight'=>'M'),
            array('name'=>'Brazilian Terrier','weight'=>'S'),
            array('name'=>'Briard','weight'=>'L'),
            array('name'=>'Briquet Griffon Vendeen','weight'=>'M'),
            array('name'=>'Brussels Griffon','weight'=>'S'),
            array('name'=>'Bukovina Sheepdog','weight'=>'L'),
            array('name'=>'Bulgarian Shepherd Dog','weight'=>'L'),
            array('name'=>'Bull Terrier','weight'=>'M'),
            array('name'=>'Bulldog','weight'=>'M'),
            array('name'=>'Bullmastiff','weight'=>'L'),
            array('name'=>'Cão da Serra de Aires','weight'=>'M'),
            array('name'=>'Cairn Terrier','weight'=>'S'),
            array('name'=>'Canaan Dog','weight'=>'M'),
            array('name'=>'Canadian Eskimo Dog','weight'=>'L'),
            array('name'=>'Cane Corso Italiano','weight'=>'L'),
            array('name'=>'Caravan Hound','weight'=>'L'),
            array('name'=>'Cardigan Welsh Corgi','weight'=>'S'),
            array('name'=>'Carolina Dog','weight'=>'M'),
            array('name'=>'Carpathian Sheepdog','weight'=>'L'),
            array('name'=>'Catahoula Bulldog','weight'=>''),
            array('name'=>'Catahoula Cur','weight'=>'M'),
            array('name'=>'Catahoula Leopard Dog','weight'=>'M'),
            array('name'=>'Catalan Sheepdog','weight'=>'M'),
            array('name'=>'Caucasian Ovtcharka','weight'=>'XL'),
            array('name'=>'Cavalier King Charles Spaniel','weight'=>'S'),
            array('name'=>'Central Asian Ovtcharka','weight'=>'L'),
            array('name'=>'Cesky Fousek','weight'=>'M'),
            array('name'=>'Cesky Terrier','weight'=>'S'),
            array('name'=>'Chart Polski','weight'=>'L'),
            array('name'=>'Chesapeake Bay Retriever','weight'=>'L'),
            array('name'=>'Chihuahua','weight'=>'S'),
            array('name'=>'Chinese Crested','weight'=>'S'),
            array('name'=>'Chow Chow','weight'=>'M'),
            array('name'=>'Cirneco Dell Etna','weight'=>'M'),
            array('name'=>'Clumber Spaniel','weight'=>'M'),
            array('name'=>'Cockapoo','weight'=>'S'),
            array('name'=>'Coton De Tulear','weight'=>'S'),
            array('name'=>'Croatian Sheepdog','weight'=>'M'),
            array('name'=>'Curly-Coated Retriever','weight'=>'L'),
            array('name'=>'Czechoslovakian Wolfdog','weight'=>'L'),
            array('name'=>'Dachshund','weight'=>'S'),
            array('name'=>'Dalmatian','weight'=>'L'),
            array('name'=>'Dandie Dinmont Terrier','weight'=>'S'),
            array('name'=>'Danish-Swedish Farmdog','weight'=>'M'),
            array('name'=>'Deutsche Bracke','weight'=>'M'),
            array('name'=>'Dingo','weight'=>'M'),
            array('name'=>'Doberman Pinscher','weight'=>'L'),
            array('name'=>'Dogue de Bordeaux','weight'=>'L'),
            array('name'=>'Drentse Patrijshond','weight'=>'M'),
            array('name'=>'Drever','weight'=>'S'),
            array('name'=>'Dunker','weight'=>'M'),
            array('name'=>'Dutch Shepherd Dog','weight'=>'L'),
            array('name'=>'Dutch Smoushond','weight'=>'S'),
            array('name'=>'East Siberian Laika','weight'=>'M'),
            array('name'=>'East-European Shepherd','weight'=>'L'),
            array('name'=>'English Coonhound','weight'=>'L'),
            array('name'=>'English Foxhound','weight'=>'M'),
            array('name'=>'English Mastiff','weight'=>'L'),
            array('name'=>'English Setter','weight'=>'L'),
            array('name'=>'English Shepherd','weight'=>'M'),
            array('name'=>'English Springer Spaniel','weight'=>'M'),
            array('name'=>'Entlebucher Mountain Dog','weight'=>'M'),
            array('name'=>'Eurasier','weight'=>'M'),
            array('name'=>'Field Spaniel','weight'=>'M'),
            array('name'=>'Fila Brasileiro','weight'=>'L'),
            array('name'=>'Finnish Hound','weight'=>'M'),
            array('name'=>'Finnish Lapphund','weight'=>'M'),
            array('name'=>'Finnish Spitz','weight'=>'M'),
            array('name'=>'Flat-Coated Retriever','weight'=>'L'),
            array('name'=>'Francais Blanc et Noir','weight'=>'L'),
            array('name'=>'French Brittany','weight'=>'M'),
            array('name'=>'French Bulldog','weight'=>'S'),
            array('name'=>'French Spaniel','weight'=>'M'),
            array('name'=>'German Longhaired Pointer','weight'=>'L'),
            array('name'=>'German Pinscher','weight'=>'M'),
            array('name'=>'German Shepherd Dog','weight'=>'L'),
            array('name'=>'German Shorthaired Pointer','weight'=>'L'),
            array('name'=>'German Wirehaired Pointer','weight'=>'M '),
            array('name'=>'Giant Schnauzer','weight'=>'XL'),
            array('name'=>'Glen of Imaal Terrier','weight'=>'S'),
            array('name'=>'Golden Retriever','weight'=>'L'),
            array('name'=>'Goldendoodle','weight'=>'S'),
            array('name'=>'Gordon Setter','weight'=>'L'),
            array('name'=>'Grand Basset Griffon Vendeen','weight'=>'M'),
            array('name'=>'Great Dane','weight'=>'L'),
            array('name'=>'Great Pyrenees','weight'=>'XL'),
            array('name'=>'Greater Swiss Mountain Dog','weight'=>'L'),
            array('name'=>'Greenland Dog','weight'=>'L'),
            array('name'=>'Greyhound','weight'=>'XL'),
            array('name'=>'Griffon bleu de Gascogne','weight'=>'M'),
            array('name'=>'Groenendael','weight'=>'L'),
            array('name'=>'Hamilton Hound','weight'=>'M'),
            array('name'=>'Harrier dog','weight'=>'M'),
            array('name'=>'Havanese','weight'=>'S'),
            array('name'=>'Hokkaido Dog','weight'=>'M'),
            array('name'=>'Hovawart','weight'=>'M'),
            array('name'=>'Ibizan Hound','weight'=>'L'),
            array('name'=>'Icelandic Sheepdog','weight'=>'M'),
            array('name'=>'Irish Red and White Setter','weight'=>'L'),
            array('name'=>'Irish Setter','weight'=>'L'),
            array('name'=>'Irish Terrier','weight'=>'S'),
            array('name'=>'Irish Water Spaniel','weight'=>'M'),
            array('name'=>'Irish Wolfhound','weight'=>'XL'),
            array('name'=>'Italian Greyhound','weight'=>'S'),
            array('name'=>'Jack Russell Terrier','weight'=>'S'),
            array('name'=>'Jagdterrier','weight'=>'S'),
            array('name'=>'Jamthund (Swedish Elkhound)','weight'=>'M'),
            array('name'=>'Japanese Chin','weight'=>'S'),
            array('name'=>'Japanese Spitz','weight'=>'S'),
            array('name'=>'Japanese Terrier','weight'=>'S'),
            array('name'=>'Karelian Bear Dog','weight'=>'M'),
            array('name'=>'Keeshond','weight'=>'S'),
            array('name'=>'Kerry Blue Terrier','weight'=>'M'),
            array('name'=>'Kishu','weight'=>'M'),
            array('name'=>'Komondor','weight'=>'L'),
            array('name'=>'Kooikerhondje','weight'=>'S'),
            array('name'=>'Koolie','weight'=>'M'),
            array('name'=>'Korean Jindo Dog','weight'=>'M'),
            array('name'=>'Kromfohrlander','weight'=>'M'),
            array('name'=>'Kuvasz','weight'=>'XL'),
            array('name'=>'Labrador Retriever','weight'=>'M'),
            array('name'=>'Lagotto Romagnolo','weight'=>'M'),
            array('name'=>'Lakeland Terrier','weight'=>'S'),
            array('name'=>'Lancashire Heeler','weight'=>'S'),
            array('name'=>'Landseer','weight'=>'XL'),
            array('name'=>'Lapponian Herder','weight'=>'M'),
            array('name'=>'Large Munsterlander','weight'=>'L'),
            array('name'=>'Leonberger','weight'=>'XL'),
            array('name'=>'Lhasa Apso','weight'=>'S'),
            array('name'=>'Lowchen','weight'=>'S'),
            array('name'=>'Maltese Dog','weight'=>'S'),
            array('name'=>'Manchester Terrier','weight'=>'S'),
            array('name'=>'McNab','weight'=>'M'),
            array('name'=>'Miniature Bull Terrier','weight'=>'S'),
            array('name'=>'Miniature Pinscher','weight'=>'S'),
            array('name'=>'Miniature Schnauzer','weight'=>'S'),
            array('name'=>'Mudi','weight'=>'M'),
            array('name'=>'Neapolitan Mastiff','weight'=>'L'),
            array('name'=>'New Guinea Singing Dog','weight'=>'M'),
            array('name'=>'Newfoundland','weight'=>'XL'),
            array('name'=>'Norfolk Terrier','weight'=>'S'),
            array('name'=>'Norrbottenspets','weight'=>'M'),
            array('name'=>'Northern Inuit Dog','weight'=>'L'),
            array('name'=>'Norwegian Buhund','weight'=>'M'),
            array('name'=>'Norwegian Elkhound','weight'=>'M'),
            array('name'=>'Norwegian Lundehund','weight'=>'S'),
            array('name'=>'Norwich Terrier','weight'=>'S'),
            array('name'=>'Old English Sheepdog','weight'=>'L'),
            array('name'=>'Olde English Bulldogge','weight'=>'L'),
            array('name'=>'Otterhound','weight'=>'L'),
            array('name'=>'Pakistani Mastiff','weight'=>'XL'),
            array('name'=>'Papillon dog','weight'=>'S'),
            array('name'=>'Parson Russell Terrier','weight'=>'S'),
            array('name'=>'Patterdale Terrier','weight'=>'S'),
            array('name'=>'Pekingese','weight'=>'S'),
            array('name'=>'Pembroke Welsh Corgi','weight'=>'S'),
            array('name'=>'Perro de Presa Canario','weight'=>'L'),
            array('name'=>'Perro de Presa Mallorquin','weight'=>'M'),
            array('name'=>'Peruvian Inca Orchid','weight'=>'M'),
            array('name'=>'Petit Basset Griffon Vendeen','weight'=>'S'),
            array('name'=>'Pharaoh Hound','weight'=>'L'),
            array('name'=>'Picardy Spaniel','weight'=>'L'),
            array('name'=>'Plott Hound','weight'=>'M'),
            array('name'=>'Plummer Terrier','weight'=>'S'),
            array('name'=>'Polish Hunting Dog','weight'=>'M'),
            array('name'=>'Polish Lowland Sheepdog','weight'=>'M'),
            array('name'=>'Pomeranian','weight'=>'S'),
            array('name'=>'Pont-Audemer Spaniel','weight'=>'M'),
            array('name'=>'Poodle','weight'=>'S'),
            array('name'=>'Portuguese Podengo','weight'=>'M'),
            array('name'=>'Portuguese Pointer','weight'=>'M'),
            array('name'=>'Portuguese Water Dog','weight'=>'M'),
            array('name'=>'Prazsky Krysarik','weight'=>'M'),
            array('name'=>'Pudelpointer','weight'=>'L'),
            array('name'=>'Pug','weight'=>'S'),
            array('name'=>'Puli,Pulik','weight'=>'M'),
            array('name'=>'Pumi','weight'=>'M'),
            array('name'=>'Pyrenean Shepherd','weight'=>'M'),
            array('name'=>'Rafeiro do Alentejo','weight'=>'L'),
            array('name'=>'Rajapalyam dog','weight'=>'L'),
            array('name'=>'Rat Terrier','weight'=>'S'),
            array('name'=>'Redbone Coonhound','weight'=>'M'),
            array('name'=>'Rhodesian Ridgeback','weight'=>'L'),
            array('name'=>'Rottweiler','weight'=>'L'),
            array('name'=>'Rough Collie','weight'=>'M'),
            array('name'=>'Russian Spaniel','weight'=>'S'),
            array('name'=>'Russian Toy','weight'=>'S'),
            array('name'=>'Saarloos wolfdog','weight'=>'L'),
            array('name'=>'Saluki','weight'=>'L'),
            array('name'=>'Samoyed','weight'=>'M'),
            array('name'=>'Sapsali','weight'=>'M'),
            array('name'=>'Sarplaninac','weight'=>'M'),
            array('name'=>'Schapendoes','weight'=>'M'),
            array('name'=>'Schipperke','weight'=>'S'),
            array('name'=>'Scottish Deerhound','weight'=>'XL'),
            array('name'=>'Scottish Terrier','weight'=>'S'),
            array('name'=>'Sealyham Terrier','weight'=>'S'),
            array('name'=>'Seppala Siberian Sleddog','weight'=>'M'),
            array('name'=>'Serbian Hound','weight'=>'M'),
            array('name'=>'Shar-Pei','weight'=>'M'),
            array('name'=>'Shetland Sheepdog','weight'=>'M '),
            array('name'=>'Shiba Inu','weight'=>'S'),
            array('name'=>'Shih Tzu','weight'=>'S'),
            array('name'=>'Shikoku dog','weight'=>'M'),
            array('name'=>'Shiloh Shepherd dog','weight'=>'M'),
            array('name'=>'Siberian Husky','weight'=>'M'),
            array('name'=>'Silken Windhound','weight'=>'M'),
            array('name'=>'Skye Terrier','weight'=>'S'),
            array('name'=>'Sloughi','weight'=>'L'),
            array('name'=>'Smaland Hound','weight'=>'M'),
            array('name'=>'Small Munsterlander','weight'=>'M'),
            array('name'=>'Smooth Collie','weight'=>'L'),
            array('name'=>'Smooth Fox Terrier','weight'=>'S'),
            array('name'=>'Soft-coated Wheaten Terrier','weight'=>'M'),
            array('name'=>'South Russian Ovcharka','weight'=>'L'),
            array('name'=>'Spanish Mastiff','weight'=>'XL'),
            array('name'=>'Spanish Water Dog','weight'=>'M'),
            array('name'=>'Spinone Italiano','weight'=>'L'),
            array('name'=>'St. Bernard(Saint Bernard)','weight'=>'XL'),
            array('name'=>'Staffordshire Bull Terrier','weight'=>'M'),
            array('name'=>'Standard Schnauzer','weight'=>'M'),
            array('name'=>'Sussex Spaniel','weight'=>'S'),
            array('name'=>'Swedish Lapphund','weight'=>'M'),
            array('name'=>'Swedish Vallhund','weight'=>'S'),
            array('name'=>'Tamaskan Dog','weight'=>'L'),
            array('name'=>'Thai Bangkaew Dog','weight'=>'M'),
            array('name'=>'Thai Ridgeback','weight'=>'M'),
            array('name'=>'Tibetan Mastiff','weight'=>'L'),
            array('name'=>'Tibetan Spaniel','weight'=>'S'),
            array('name'=>'Tibetan Terrier','weight'=>'M'),
            array('name'=>'Tolling Retriever','weight'=>'M'),
            array('name'=>'Tornjak','weight'=>'L'),
            array('name'=>'Tosa','weight'=>'L'),
            array('name'=>'Toy Bulldog','weight'=>'S'),
            array('name'=>'Toy Fox Terrier','weight'=>'S'),
            array('name'=>'Toy Manchester Terrier','weight'=>'S'),
            array('name'=>'Transylvanian Hound','weight'=>'M'),
            array('name'=>'Treeing Walker Coonhound','weight'=>'M'),
            array('name'=>'Vizsla','weight'=>'M'),
            array('name'=>'Volpino Italiano','weight'=>'S'),
            array('name'=>'Weimaraner','weight'=>'M'),
            array('name'=>'Welsh Springer Spaniel','weight'=>'M'),
            array('name'=>'Welsh Terrier','weight'=>'S'),
            array('name'=>'West Highland White Terrier','weight'=>'S'),
            array('name'=>'West Siberian Laika','weight'=>'L'),
            array('name'=>'Wetterhoun','weight'=>'M'),
            array('name'=>'Whippet','weight'=>'M'),
            array('name'=>'Wire Fox Terrier','weight'=>'S'),
            array('name'=>'Wirehaired Pointing Griffon','weight'=>'M'),
            array('name'=>'Xoloitzcuintle','weight'=>'S'),
            array('name'=>'Yorkshire Terrier','weight'=>'S'),

        ));
    }

}
