<?php

class DatabaseSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		Eloquent::unguard();

		$this->call('SymtomTableSeeder');
        $this->call('ConditionTableSeeder');
        $this->call('BreedTableSeeder');
	}

}

class SymtomTableSeeder extends Seeder {

    public function run()
    {
        DB::table('symptoms')->delete();

        DB::table('symptoms')->insert(array(
            array('name'=>'All looks normal'),
            array('name'=>'Itching/Scratching'),
            array('name'=>'Hair Loss'),
            array('name'=>'Diarrhea'),
            array('name'=>'Vomiting'),
            array('name'=>'Drooling'),
            array('name'=>'Urinating a lot or Urine loss'),
            array('name'=>'Restless'),
            array('name'=>'Changed appetite'),
            array('name'=>'Increased eating / Abnormal eating'),
            array('name'=>'Increased head shaking'),
            array('name'=>'Change in odor'),
            array('name'=>'Weight loss'),
            array('name'=>'Abnormal behavior'),
            array('name'=>'Not playful'),
            array('name'=>'Abnormal movement'),
            array('name'=>'Limping'),
            array('name'=>'Overall poor appearance'),
            array('name'=>'Dull Coat'),
            array('name'=>'Drinking a lot'),
            array('name'=>'Bleeding'),
            array('name'=>'Looks pale'),
            array('name'=>'Change in bark'),
        ));
    }

}

class ConditionTableSeeder extends Seeder {

    public function run()
    {
        DB::table('conditions')->delete();

        DB::table('conditions')->insert(array(
            array('name'=>'None'),
            array('name'=>'Allergic Dermatitis or other Skin Condition'),
            array('name'=>'Arthritis and Joint Pain'),
            array('name'=>'Behavioral Changes & Alertness Changes'),
            array('name'=>'Cancer'),
            array('name'=>'Dental Disease'),
            array('name'=>'Diabetes Mellitus'),
            array('name'=>'Hypothyroidism'),
            array('name'=>'Cushing’s Syndrome'),
            array('name'=>'Addison’s Disease'),
            array('name'=>'Food Allergy or Food Intolerance'),
            array('name'=>'Gastrointestinal or Digestive Disorder'),
            array('name'=>'Heart Disease'),
            array('name'=>'Kidney Disease'),
            array('name'=>'Liver Disease'),
            array('name'=>'Urinary Bladder Stones'),
            array('name'=>'Incontinence'),
            array('name'=>'Previous Accident'),
            array('name'=>'Recent Surgery'),
            array('name'=>') Nervous System Disorder'),
            array('name'=>'Bone or Muscular Disorder'),
            array('name'=>'Eye Condition'),
            array('name'=>'Recurrent Ear infections'),
            array('name'=>'Tooth Problems'),
        ));
    }

}

class BreedTableSeeder extends Seeder {

    public function run()
    {
        DB::table('breeds')->delete();

        DB::table('breeds')->insert(array(
            array('name'=>'Affenpinscher','size'=>'S'),
            array('name'=>'Afghan Hound','size'=>'L'),
            array('name'=>'African Wild Dog','size'=>'M'),
            array('name'=>'Africanis','size'=>'M'),
            array('name'=>'Aidi','size'=>'M'),
            array('name'=>'Airedale Terrier','size'=>'S'),
            array('name'=>'Akbash Dog','size'=>'L'),
            array('name'=>'Alano Espanol','size'=>'L'),
            array('name'=>'Alapaha Blue Blood Bulldog','size'=>'M'),
            array('name'=>'Alaskan Husky','size'=>'L'),
            array('name'=>'Alaskan Klee Kai','size'=>'M'),
            array('name'=>'Alaskan Malamute','size'=>'L'),
            array('name'=>'Alopekis','size'=>'S'),
            array('name'=>'American Akita','size'=>'L'),
            array('name'=>'American Bulldog','size'=>'L'),
            array('name'=>'American Cocker Spaniel','size'=>'M'),
            array('name'=>'American Eskimo Dog','size'=>'M'),
            array('name'=>'American Foxhound','size'=>'L'),
            array('name'=>'American Hairless Terrier','size'=>'S'),
            array('name'=>'American Mastiff','size'=>'L'),
            array('name'=>'American Pit Bull Terrier','size'=>'M'),
            array('name'=>'American Staffordshire Terrier','size'=>'M'),
            array('name'=>'American Staghound','size'=>'L'),
            array('name'=>'American Water Spaniel','size'=>'M'),
            array('name'=>'American White Shepherd','size'=>'M'),
            array('name'=>'Anatolian Shepherd Dog','size'=>'L'),
            array('name'=>'Andalusian Hound','size'=>'M'),
            array('name'=>'Appenzeller Sennenhund','size'=>'M'),
            array('name'=>'Argentine Dogo','size'=>'L'),
            array('name'=>'Ariege Pointer','size'=>'L'),
            array('name'=>'Ariegeois','size'=>'M'),
            array('name'=>'Australian Bulldog','size'=>'M'),
            array('name'=>'Australian Cattle Dog','size'=>'M'),
            array('name'=>'Australian Kelpie','size'=>'M'),
            array('name'=>'Australian Shepherd','size'=>'M'),
            array('name'=>'Australian Silky Terrier','size'=>'S'),
            array('name'=>'Australian Stumpy Tail Cattle Dog','size'=>'M'),
            array('name'=>'Australian Terrier','size'=>'S'),
            array('name'=>'Austrian Black and Tan Hound','size'=>'M'),
            array('name'=>'Austrian Pinscher','size'=>'M'),
            array('name'=>'Azawakh','size'=>'L'),
            array('name'=>'Barbet','size'=>'M'),
            array('name'=>'Basenji','size'=>'M'),
            array('name'=>'Basset Artesien Normand','size'=>'S'),
            array('name'=>'Basset Bleu de Gascogne','size'=>'S'),
            array('name'=>'Basset Fauve de Bretagne','size'=>'S'),
            array('name'=>'Basset Hound','size'=>'M'),
            array('name'=>'Bavarian Mountain Hound','size'=>'M'),
            array('name'=>'Beagle','size'=>'S'),
            array('name'=>'Beagle-Harrier','size'=>'M'),
            array('name'=>'Beaglier','size'=>'M'),
            array('name'=>'Bearded Collie','size'=>'M'),
            array('name'=>'Beauceron','size'=>'L'),
            array('name'=>'Bedlington Terrier','size'=>'S'),
            array('name'=>'Belgian Shepherd Laekenois','size'=>'M'),
            array('name'=>'Belgian Shepherd Malinois','size'=>'M'),
            array('name'=>'Belgian Shepherd Tervuren','size'=>'M'),
            array('name'=>'Bergamasco','size'=>'M'),
            array('name'=>'Berger Picard','size'=>'M'),
            array('name'=>'Bernese Mountain Dog','size'=>'L'),
            array('name'=>'Bichon Frise','size'=>'S'),
            array('name'=>'Black and Tan Coonhound','size'=>'L'),
            array('name'=>'Black Norwegian Elkhound','size'=>'S'),
            array('name'=>'Black Russian Terrier','size'=>'L'),
            array('name'=>'Blackmouth Cur','size'=>'M'),
            array('name'=>'Bloodhound','size'=>'L'),
            array('name'=>'Blue Lacy','size'=>'M'),
            array('name'=>'Blue Picardy Spaniel','size'=>'L'),
            array('name'=>'Bluetick Coonhound','size'=>'M'),
            array('name'=>'Boerboel','size'=>'L'),
            array('name'=>'Bohemian Shepherd','size'=>'M'),
            array('name'=>'Bolognese dog','size'=>'S'),
            array('name'=>'Border Collie','size'=>'M'),
            array('name'=>'Border Terrier','size'=>'S'),
            array('name'=>'Borzoi','size'=>'XL'),
            array('name'=>'Boston Terrier','size'=>'S'),
            array('name'=>'Bouvier de Ardennes','size'=>'M'),
            array('name'=>'Bouvier des Flanders','size'=>'L'),
            array('name'=>'Boxer','size'=>'M'),
            array('name'=>'Boykin Spaniel','size'=>'M'),
            array('name'=>'Bracco Italiano','size'=>'L'),
            array('name'=>'Braque du Bourbonnais','size'=>'M'),
            array('name'=>'Brazilian Terrier','size'=>'S'),
            array('name'=>'Briard','size'=>'L'),
            array('name'=>'Briquet Griffon Vendeen','size'=>'M'),
            array('name'=>'Brussels Griffon','size'=>'S'),
            array('name'=>'Bukovina Sheepdog','size'=>'L'),
            array('name'=>'Bulgarian Shepherd Dog','size'=>'L'),
            array('name'=>'Bull Terrier','size'=>'M'),
            array('name'=>'Bulldog','size'=>'M'),
            array('name'=>'Bullmastiff','size'=>'L'),
            array('name'=>'Cão da Serra de Aires','size'=>'M'),
            array('name'=>'Cairn Terrier','size'=>'S'),
            array('name'=>'Canaan Dog','size'=>'M'),
            array('name'=>'Canadian Eskimo Dog','size'=>'L'),
            array('name'=>'Cane Corso Italiano','size'=>'L'),
            array('name'=>'Caravan Hound','size'=>'L'),
            array('name'=>'Cardigan Welsh Corgi','size'=>'S'),
            array('name'=>'Carolina Dog','size'=>'M'),
            array('name'=>'Carpathian Sheepdog','size'=>'L'),
            array('name'=>'Catahoula Bulldog','size'=>''),
            array('name'=>'Catahoula Cur','size'=>'M'),
            array('name'=>'Catahoula Leopard Dog','size'=>'M'),
            array('name'=>'Catalan Sheepdog','size'=>'M'),
            array('name'=>'Caucasian Ovtcharka','size'=>'XL'),
            array('name'=>'Cavalier King Charles Spaniel','size'=>'S'),
            array('name'=>'Central Asian Ovtcharka','size'=>'L'),
            array('name'=>'Cesky Fousek','size'=>'M'),
            array('name'=>'Cesky Terrier','size'=>'S'),
            array('name'=>'Chart Polski','size'=>'L'),
            array('name'=>'Chesapeake Bay Retriever','size'=>'L'),
            array('name'=>'Chihuahua','size'=>'S'),
            array('name'=>'Chinese Crested','size'=>'S'),
            array('name'=>'Chow Chow','size'=>'M'),
            array('name'=>'Cirneco Dell Etna','size'=>'M'),
            array('name'=>'Clumber Spaniel','size'=>'M'),
            array('name'=>'Cockapoo','size'=>'S'),
            array('name'=>'Coton De Tulear','size'=>'S'),
            array('name'=>'Croatian Sheepdog','size'=>'M'),
            array('name'=>'Curly-Coated Retriever','size'=>'L'),
            array('name'=>'Czechoslovakian Wolfdog','size'=>'L'),
            array('name'=>'Dachshund','size'=>'S'),
            array('name'=>'Dalmatian','size'=>'L'),
            array('name'=>'Dandie Dinmont Terrier','size'=>'S'),
            array('name'=>'Danish-Swedish Farmdog','size'=>'M'),
            array('name'=>'Deutsche Bracke','size'=>'M'),
            array('name'=>'Dingo','size'=>'M'),
            array('name'=>'Doberman Pinscher','size'=>'L'),
            array('name'=>'Dogue de Bordeaux','size'=>'L'),
            array('name'=>'Drentse Patrijshond','size'=>'M'),
            array('name'=>'Drever','size'=>'S'),
            array('name'=>'Dunker','size'=>'M'),
            array('name'=>'Dutch Shepherd Dog','size'=>'L'),
            array('name'=>'Dutch Smoushond','size'=>'S'),
            array('name'=>'East Siberian Laika','size'=>'M'),
            array('name'=>'East-European Shepherd','size'=>'L'),
            array('name'=>'English Coonhound','size'=>'L'),
            array('name'=>'English Foxhound','size'=>'M'),
            array('name'=>'English Mastiff','size'=>'L'),
            array('name'=>'English Setter','size'=>'L'),
            array('name'=>'English Shepherd','size'=>'M'),
            array('name'=>'English Springer Spaniel','size'=>'M'),
            array('name'=>'Entlebucher Mountain Dog','size'=>'M'),
            array('name'=>'Eurasier','size'=>'M'),
            array('name'=>'Field Spaniel','size'=>'M'),
            array('name'=>'Fila Brasileiro','size'=>'L'),
            array('name'=>'Finnish Hound','size'=>'M'),
            array('name'=>'Finnish Lapphund','size'=>'M'),
            array('name'=>'Finnish Spitz','size'=>'M'),
            array('name'=>'Flat-Coated Retriever','size'=>'L'),
            array('name'=>'Francais Blanc et Noir','size'=>'L'),
            array('name'=>'French Brittany','size'=>'M'),
            array('name'=>'French Bulldog','size'=>'S'),
            array('name'=>'French Spaniel','size'=>'M'),
            array('name'=>'German Longhaired Pointer','size'=>'L'),
            array('name'=>'German Pinscher','size'=>'M'),
            array('name'=>'German Shepherd Dog','size'=>'L'),
            array('name'=>'German Shorthaired Pointer','size'=>'L'),
            array('name'=>'German Wirehaired Pointer','size'=>'M '),
            array('name'=>'Giant Schnauzer','size'=>'XL'),
            array('name'=>'Glen of Imaal Terrier','size'=>'S'),
            array('name'=>'Golden Retriever','size'=>'L'),
            array('name'=>'Goldendoodle','size'=>'S'),
            array('name'=>'Gordon Setter','size'=>'L'),
            array('name'=>'Grand Basset Griffon Vendeen','size'=>'M'),
            array('name'=>'Great Dane','size'=>'L'),
            array('name'=>'Great Pyrenees','size'=>'XL'),
            array('name'=>'Greater Swiss Mountain Dog','size'=>'L'),
            array('name'=>'Greenland Dog','size'=>'L'),
            array('name'=>'Greyhound','size'=>'XL'),
            array('name'=>'Griffon bleu de Gascogne','size'=>'M'),
            array('name'=>'Groenendael','size'=>'L'),
            array('name'=>'Hamilton Hound','size'=>'M'),
            array('name'=>'Harrier dog','size'=>'M'),
            array('name'=>'Havanese','size'=>'S'),
            array('name'=>'Hokkaido Dog','size'=>'M'),
            array('name'=>'Hovawart','size'=>'M'),
            array('name'=>'Ibizan Hound','size'=>'L'),
            array('name'=>'Icelandic Sheepdog','size'=>'M'),
            array('name'=>'Irish Red and White Setter','size'=>'L'),
            array('name'=>'Irish Setter','size'=>'L'),
            array('name'=>'Irish Terrier','size'=>'S'),
            array('name'=>'Irish Water Spaniel','size'=>'M'),
            array('name'=>'Irish Wolfhound','size'=>'XL'),
            array('name'=>'Italian Greyhound','size'=>'S'),
            array('name'=>'Jack Russell Terrier','size'=>'S'),
            array('name'=>'Jagdterrier','size'=>'S'),
            array('name'=>'Jamthund (Swedish Elkhound)','size'=>'M'),
            array('name'=>'Japanese Chin','size'=>'S'),
            array('name'=>'Japanese Spitz','size'=>'S'),
            array('name'=>'Japanese Terrier','size'=>'S'),
            array('name'=>'Karelian Bear Dog','size'=>'M'),
            array('name'=>'Keeshond','size'=>'S'),
            array('name'=>'Kerry Blue Terrier','size'=>'M'),
            array('name'=>'Kishu','size'=>'M'),
            array('name'=>'Komondor','size'=>'L'),
            array('name'=>'Kooikerhondje','size'=>'S'),
            array('name'=>'Koolie','size'=>'M'),
            array('name'=>'Korean Jindo Dog','size'=>'M'),
            array('name'=>'Kromfohrlander','size'=>'M'),
            array('name'=>'Kuvasz','size'=>'XL'),
            array('name'=>'Labrador Retriever','size'=>'M'),
            array('name'=>'Lagotto Romagnolo','size'=>'M'),
            array('name'=>'Lakeland Terrier','size'=>'S'),
            array('name'=>'Lancashire Heeler','size'=>'S'),
            array('name'=>'Landseer','size'=>'XL'),
            array('name'=>'Lapponian Herder','size'=>'M'),
            array('name'=>'Large Munsterlander','size'=>'L'),
            array('name'=>'Leonberger','size'=>'XL'),
            array('name'=>'Lhasa Apso','size'=>'S'),
            array('name'=>'Lowchen','size'=>'S'),
            array('name'=>'Maltese Dog','size'=>'S'),
            array('name'=>'Manchester Terrier','size'=>'S'),
            array('name'=>'McNab','size'=>'M'),
            array('name'=>'Miniature Bull Terrier','size'=>'S'),
            array('name'=>'Miniature Pinscher','size'=>'S'),
            array('name'=>'Miniature Schnauzer','size'=>'S'),
            array('name'=>'Mudi','size'=>'M'),
            array('name'=>'Neapolitan Mastiff','size'=>'L'),
            array('name'=>'New Guinea Singing Dog','size'=>'M'),
            array('name'=>'Newfoundland','size'=>'XL'),
            array('name'=>'Norfolk Terrier','size'=>'S'),
            array('name'=>'Norrbottenspets','size'=>'M'),
            array('name'=>'Northern Inuit Dog','size'=>'L'),
            array('name'=>'Norwegian Buhund','size'=>'M'),
            array('name'=>'Norwegian Elkhound','size'=>'M'),
            array('name'=>'Norwegian Lundehund','size'=>'S'),
            array('name'=>'Norwich Terrier','size'=>'S'),
            array('name'=>'Old English Sheepdog','size'=>'L'),
            array('name'=>'Olde English Bulldogge','size'=>'L'),
            array('name'=>'Otterhound','size'=>'L'),
            array('name'=>'Pakistani Mastiff','size'=>'XL'),
            array('name'=>'Papillon dog','size'=>'S'),
            array('name'=>'Parson Russell Terrier','size'=>'S'),
            array('name'=>'Patterdale Terrier','size'=>'S'),
            array('name'=>'Pekingese','size'=>'S'),
            array('name'=>'Pembroke Welsh Corgi','size'=>'S'),
            array('name'=>'Perro de Presa Canario','size'=>'L'),
            array('name'=>'Perro de Presa Mallorquin','size'=>'M'),
            array('name'=>'Peruvian Inca Orchid','size'=>'M'),
            array('name'=>'Petit Basset Griffon Vendeen','size'=>'S'),
            array('name'=>'Pharaoh Hound','size'=>'L'),
            array('name'=>'Picardy Spaniel','size'=>'L'),
            array('name'=>'Plott Hound','size'=>'M'),
            array('name'=>'Plummer Terrier','size'=>'S'),
            array('name'=>'Polish Hunting Dog','size'=>'M'),
            array('name'=>'Polish Lowland Sheepdog','size'=>'M'),
            array('name'=>'Pomeranian','size'=>'S'),
            array('name'=>'Pont-Audemer Spaniel','size'=>'M'),
            array('name'=>'Poodle','size'=>'S'),
            array('name'=>'Portuguese Podengo','size'=>'M'),
            array('name'=>'Portuguese Pointer','size'=>'M'),
            array('name'=>'Portuguese Water Dog','size'=>'M'),
            array('name'=>'Prazsky Krysarik','size'=>'M'),
            array('name'=>'Pudelpointer','size'=>'L'),
            array('name'=>'Pug','size'=>'S'),
            array('name'=>'Puli,Pulik','size'=>'M'),
            array('name'=>'Pumi','size'=>'M'),
            array('name'=>'Pyrenean Shepherd','size'=>'M'),
            array('name'=>'Rafeiro do Alentejo','size'=>'L'),
            array('name'=>'Rajapalyam dog','size'=>'L'),
            array('name'=>'Rat Terrier','size'=>'S'),
            array('name'=>'Redbone Coonhound','size'=>'M'),
            array('name'=>'Rhodesian Ridgeback','size'=>'L'),
            array('name'=>'Rottweiler','size'=>'L'),
            array('name'=>'Rough Collie','size'=>'M'),
            array('name'=>'Russian Spaniel','size'=>'S'),
            array('name'=>'Russian Toy','size'=>'S'),
            array('name'=>'Saarloos wolfdog','size'=>'L'),
            array('name'=>'Saluki','size'=>'L'),
            array('name'=>'Samoyed','size'=>'M'),
            array('name'=>'Sapsali','size'=>'M'),
            array('name'=>'Sarplaninac','size'=>'M'),
            array('name'=>'Schapendoes','size'=>'M'),
            array('name'=>'Schipperke','size'=>'S'),
            array('name'=>'Scottish Deerhound','size'=>'XL'),
            array('name'=>'Scottish Terrier','size'=>'S'),
            array('name'=>'Sealyham Terrier','size'=>'S'),
            array('name'=>'Seppala Siberian Sleddog','size'=>'M'),
            array('name'=>'Serbian Hound','size'=>'M'),
            array('name'=>'Shar-Pei','size'=>'M'),
            array('name'=>'Shetland Sheepdog','size'=>'M '),
            array('name'=>'Shiba Inu','size'=>'S'),
            array('name'=>'Shih Tzu','size'=>'S'),
            array('name'=>'Shikoku dog','size'=>'M'),
            array('name'=>'Shiloh Shepherd dog','size'=>'M'),
            array('name'=>'Siberian Husky','size'=>'M'),
            array('name'=>'Silken Windhound','size'=>'M'),
            array('name'=>'Skye Terrier','size'=>'S'),
            array('name'=>'Sloughi','size'=>'L'),
            array('name'=>'Smaland Hound','size'=>'M'),
            array('name'=>'Small Munsterlander','size'=>'M'),
            array('name'=>'Smooth Collie','size'=>'L'),
            array('name'=>'Smooth Fox Terrier','size'=>'S'),
            array('name'=>'Soft-coated Wheaten Terrier','size'=>'M'),
            array('name'=>'South Russian Ovcharka','size'=>'L'),
            array('name'=>'Spanish Mastiff','size'=>'XL'),
            array('name'=>'Spanish Water Dog','size'=>'M'),
            array('name'=>'Spinone Italiano','size'=>'L'),
            array('name'=>'St. Bernard(Saint Bernard)','size'=>'XL'),
            array('name'=>'Staffordshire Bull Terrier','size'=>'M'),
            array('name'=>'Standard Schnauzer','size'=>'M'),
            array('name'=>'Sussex Spaniel','size'=>'S'),
            array('name'=>'Swedish Lapphund','size'=>'M'),
            array('name'=>'Swedish Vallhund','size'=>'S'),
            array('name'=>'Tamaskan Dog','size'=>'L'),
            array('name'=>'Thai Bangkaew Dog','size'=>'M'),
            array('name'=>'Thai Ridgeback','size'=>'M'),
            array('name'=>'Tibetan Mastiff','size'=>'L'),
            array('name'=>'Tibetan Spaniel','size'=>'S'),
            array('name'=>'Tibetan Terrier','size'=>'M'),
            array('name'=>'Tolling Retriever','size'=>'M'),
            array('name'=>'Tornjak','size'=>'L'),
            array('name'=>'Tosa','size'=>'L'),
            array('name'=>'Toy Bulldog','size'=>'S'),
            array('name'=>'Toy Fox Terrier','size'=>'S'),
            array('name'=>'Toy Manchester Terrier','size'=>'S'),
            array('name'=>'Transylvanian Hound','size'=>'M'),
            array('name'=>'Treeing Walker Coonhound','size'=>'M'),
            array('name'=>'Vizsla','size'=>'M'),
            array('name'=>'Volpino Italiano','size'=>'S'),
            array('name'=>'Weimaraner','size'=>'M'),
            array('name'=>'Welsh Springer Spaniel','size'=>'M'),
            array('name'=>'Welsh Terrier','size'=>'S'),
            array('name'=>'West Highland White Terrier','size'=>'S'),
            array('name'=>'West Siberian Laika','size'=>'L'),
            array('name'=>'Wetterhoun','size'=>'M'),
            array('name'=>'Whippet','size'=>'M'),
            array('name'=>'Wire Fox Terrier','size'=>'S'),
            array('name'=>'Wirehaired Pointing Griffon','size'=>'M'),
            array('name'=>'Xoloitzcuintle','size'=>'S'),
            array('name'=>'Yorkshire Terrier','size'=>'S'),

        ));
    }

}
